curl -XPOST 'localhost:9200/test/test/' -d '  {
    "EVENT CATEGORY":"Disaster",
    "EVENT GROUP":"Natural",
    "EVENT SUBGROUP":"Meteorological - Hydrological",
    "EVENT TYPE":"Tornado",
    "PLACE":"Goderich ON",
    "EVENT START DATE":"21/08/2011 12:00:00 AM",
    "COMMENTS":"Goderich ON, August 21-22, 2011. At approximately 16:00 EDT, a Fujita Scale Three (F3: winds near 250 km/hr) tornado touched down in the town of Goderich, ON causing extensive damages including damaged roof tops, fallen trees, gas leaks and hydroelectricity outages. Natural gas was off to 90% for the town of Goderich as well as to residents in the surrounding municipalities. As of 10:30 EDT on August 22, 2011, power had been restored to most of the affected area.",
    "FATALITIES":"",
    "INJURED / INFECTED":"",
    "EVACUATED":"",
    "ESTIMATED TOTAL COST":"",
    "NORMALIZED TOTAL COST":"",
    "EVENT END DATE":"22/08/2011 12:00:00 AM",
    "FEDERAL DFAA PAYMENTS":"",
    "PROVINCIAL DFAA PAYMENTS":"",
    "PROVINCIAL DEPARTMENT PAYMENTS":"",
    "MUNICIPAL COSTS":"",
    "OGD COSTS":"",
    "INSURANCE PAYMENTS":"",
    "NGO PAYMENTS":"",
    "UTILITY - PEOPLE AFFECTED":"8000",
    "MAGNITUDE":"",
    "FIELD23":""
  }'
